{% set sha256 = "6b5ee59dc646eb61a8eb65ee1db186d3df6687c8804830024f32573298bca19b" %}
{% set version = "1.56.1" %}
{% set name = "googleapis-common-protos" %}

package:
  name: {{ name|lower }}-feedstock
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win and vc<14]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip >=18.1
    - setuptools >=34.0.0

outputs:
  - name: {{ name }}
    build:
      script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --verbose
      skip: true  # [win and vc<14]
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - python
        - pip >=18.1
        - protobuf >=3.12.0
        - setuptools >=34.0.0
      run:
        - python
        - protobuf >=3.12.0
    test:
      imports:
        - google.api
        - google.api.annotations_pb2
        - google.api.auth_pb2
        - google.api.backend_pb2
        - google.api.billing_pb2
        - google.api.client_pb2
        - google.api.config_change_pb2
        - google.api.consumer_pb2
        - google.api.context_pb2
        - google.api.control_pb2
        - google.api.distribution_pb2
        - google.api.documentation_pb2
        - google.api.endpoint_pb2
        - google.api.field_behavior_pb2
        - google.api.http_pb2
        - google.api.httpbody_pb2
        - google.api.label_pb2
        - google.api.launch_stage_pb2
        - google.api.log_pb2
        - google.api.logging_pb2
        - google.api.metric_pb2
        - google.api.monitored_resource_pb2
        - google.api.monitoring_pb2
        - google.api.quota_pb2
        - google.api.resource_pb2
        - google.api.service_pb2
        - google.api.source_info_pb2
        - google.api.system_parameter_pb2
        - google.api.usage_pb2
        - google.longrunning
        - google.longrunning.operations_pb2
        - google.longrunning.operations_proto
        - google.longrunning.operations_proto_pb2
        - google.rpc
        - google.rpc.code_pb2
        - google.rpc.error_details_pb2
        - google.rpc.status_pb2
        - google.type
        - google.type.calendar_period_pb2
        - google.type.color_pb2
        - google.type.date_pb2
        - google.type.dayofweek_pb2
        - google.type.expr_pb2
        - google.type.fraction_pb2
        - google.type.latlng_pb2
        - google.type.money_pb2
        - google.type.postal_address_pb2
        - google.type.quaternion_pb2
        - google.type.timeofday_pb2

  - name: {{ name }}-grpc
    build:
      skip: true  # [win and vc<14]
    requirements:
      host:
        - python
        - grpcio >=1.0.0
      run:
        - {{ pin_subpackage(name, min_pin='x.x', max_pin='x.x') }}
        - grpcio >=1.0.0
    test:
      imports:
        - google.api
        - google.api.annotations_pb2
        - google.api.auth_pb2
        - google.api.backend_pb2
        - google.api.billing_pb2
        - google.api.client_pb2
        - google.api.config_change_pb2
        - google.api.consumer_pb2
        - google.api.context_pb2
        - google.api.control_pb2
        - google.api.distribution_pb2
        - google.api.documentation_pb2
        - google.api.endpoint_pb2
        - google.api.field_behavior_pb2
        - google.api.http_pb2
        - google.api.httpbody_pb2
        - google.api.label_pb2
        - google.api.launch_stage_pb2
        - google.api.log_pb2
        - google.api.logging_pb2
        - google.api.metric_pb2
        - google.api.monitored_resource_pb2
        - google.api.monitoring_pb2
        - google.api.quota_pb2
        - google.api.resource_pb2
        - google.api.service_pb2
        - google.api.source_info_pb2
        - google.api.system_parameter_pb2
        - google.api.usage_pb2
        - google.longrunning
        - google.longrunning.operations_grpc
        - google.longrunning.operations_grpc_pb2
        - google.longrunning.operations_pb2
        - google.longrunning.operations_proto
        - google.longrunning.operations_proto_pb2
        - google.rpc
        - google.rpc.code_pb2
        - google.rpc.error_details_pb2
        - google.rpc.status_pb2
        - google.type
        - google.type.calendar_period_pb2
        - google.type.color_pb2
        - google.type.date_pb2
        - google.type.dayofweek_pb2
        - google.type.expr_pb2
        - google.type.fraction_pb2
        - google.type.latlng_pb2
        - google.type.money_pb2
        - google.type.postal_address_pb2
        - google.type.quaternion_pb2
        - google.type.timeofday_pb2
    about:
      home: https://github.com/googleapis/api-common-protos
      license: Apache-2.0
      license_file: LICENSE
      license_family: APACHE
      summary: Common protobufs used in Google APIs
      description: |
        {{ name }}-grpc installs {{ name }} and the grpc extra requirements.

        This repository contains the original interface definitions of public
        Google APIs that support both REST and gRPC protocols. Reading the original
        interface definitions can provide a better understanding of Google APIs and
        help you to utilize them more efficiently. You can also use these definitions
        with open source tools to generate client libraries, documentation,
        and other artifacts.

        **Deprecated Python Versions**

        Python == 2.7
        - Python 2.7 support will be removed on January 1, 2020.
        - protobuf does not support Visual C++ 2008, windows py27 package not available

      doc_url: https://github.com/googleapis/api-common-protos/blob/master/README.md
      dev_url: https://github.com/googleapis/api-common-protos

about:
  home: https://github.com/googleapis/api-common-protos
  license: Apache-2.0
  license_file: LICENSE
  license_family: APACHE
  summary: Common protobufs used in Google APIs
  description: |
    This package does not include the grpc extra requirements.

    This repository contains the original interface definitions of public
    Google APIs that support both REST and gRPC protocols. Reading the original
    interface definitions can provide a better understanding of Google APIs and
    help you to utilize them more efficiently. You can also use these definitions
    with open source tools to generate client libraries, documentation,
    and other artifacts.

    **Deprecated Python Versions**

    Python == 2.7
    - Python 2.7 support will be removed on January 1, 2020.
    - protobuf does not support Visual C++ 2008, windows py27 package not available

  doc_url: https://github.com/googleapis/python-api-common-protos/blob/main/README.md
  dev_url: https://github.com/googleapis/python-api-common-protos

extra:
  recipe-maintainers:
    - BrentDorsey
    - leahecole
    - parthea
    - tswast
